# Generated by Django 4.1.1 on 2023-04-06 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("image_url", models.URLField(blank=True)),
                ("filename", models.CharField(max_length=100, unique=True)),
                ("starting_bid", models.IntegerField()),
                ("category", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("date", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("a", "active"), ("n", "non-active")],
                        default="a",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
