# Generated by Django 4.1.1 on 2023-04-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_listing_current_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="User1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watchlist",
                    models.ManyToManyField(blank=True, to="auctions.listing"),
                ),
            ],
        ),
    ]
