# Generated by Django 4.1.1 on 2023-04-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_bid_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="current_bidder",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
