# Generated by Django 4.1.1 on 2023-04-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_listing_current_bidder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="comment", new_name="content",
        ),
    ]
