# Generated by Django 4.1.1 on 2023-04-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_alter_listing_current_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="current_price",
            field=models.IntegerField(default=0),
        ),
    ]
