# Generated by Django 4.1.1 on 2023-04-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_listing_current_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("h", "Furniture"),
                    ("a", "Auto"),
                    ("e", "Electronics"),
                    ("Others", "Others"),
                ],
                default="Others",
                max_length=12,
            ),
        ),
    ]
