# Generated by Django 4.1.1 on 2023-04-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_alter_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("Furniture", "Furniture"),
                    ("Auto", "Auto"),
                    ("Antiques", "Antiques"),
                    ("Accessories", "Accessories"),
                    ("Others", "Others"),
                ],
                default="Others",
                max_length=12,
            ),
        ),
    ]
