# Generated by Django 4.1.1 on 2023-04-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_alter_bid_listing"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="date",),
    ]
