# Generated by Django 4.1.1 on 2023-04-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_remove_listing_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="bid", name="status",),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("No category", "No category"),
                    ("Furniture", "Furniture"),
                    ("Auto", "Auto"),
                    ("Antiques", "Antiques"),
                    ("Accessories", "Accessories"),
                    ("Art", "Art"),
                    ("Others", "Others"),
                ],
                default="Others",
                max_length=12,
            ),
        ),
    ]
